export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_PENDING_FOR_NEXT = 'SEARCH_PENDING_FOR_NEXT';
export const SEARCH_DONE = 'SEARCH_DONE';
export const SEARCH_SAVE = 'SEARCH_SAVE';
export const IDLE = 'IDLE';
